services:
  search_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads

  asreview:
    image: "joshmvarghese/my_asreview:latest"
    volumes:
      - ./uploads:/app/uploads  # Change this line to match the search_app uploads directory
      - ./asreview_config.toml:/app/asreview_config.toml
    environment:
      - ASREVIEW_LAB_API_URL=/
      - ASREVIEW_LAB_CONFIG_PATH=/app/asreview_config.toml
      - ASREVIEW_PATH=/app/uploads  # Update ASREVIEW_PATH to the new uploads directory
    ports:
      - "5001:5001"
    entrypoint: /bin/sh -c "mkdir -p /app/uploads && exec asreview lab --port 5001 --host 0.0.0.0"

  server:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./asreview.conf:/etc/nginx/nginx.conf
    depends_on:
      - asreview
